In [2]:
import numpy as np

In [3]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
import pandas

In [5]:
data = pandas.read_csv('/home/stas/data/titanic.csv', index_col='PassengerId')

In [23]:
clf=DecisionTreeClassifier(random_state=241)

In [8]:
x=np.array([[1,2],[3,4],[5,6]])

In [9]:
y=np.array([0,1,0])

In [10]:
clf.fit(x,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [94]:
importances=clf.feature_importances_

In [97]:
frame=data.loc[:,["Sex","Pclass","Age","Fare"]]

In [91]:
frame=frame.dropna(how="any")

In [98]:
%%time
for i in range(1,len(frame["Sex"])+1):
    if frame["Sex"][i]=="male":
        frame["Sex"][i]=0
    else: 
        frame["Sex"][i]=1

/home/stas/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/home/stas/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

CPU times: user 33.8 s, sys: 4 ms, total: 33.8 s
Wall time: 33.8 s

In [85]:
main=frame["Survived"]

In [93]:
clf.fit(frame,main)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=241, splitter='best')

In [95]:
importances

array([ 0.30051221,  0.14751816,  0.25124241,  0.30072722])

In [96]:
frame

            Sex  Pclass   Age      Fare
PassengerId
1             0       3  22.0    7.2500
2             1       1  38.0   71.2833
3             1       3  26.0    7.9250
4             1       1  35.0   53.1000
5             0       3  35.0    8.0500
7             0       1  54.0   51.8625
8             0       3   2.0   21.0750
9             1       3  27.0   11.1333
10            1       2  14.0   30.0708
11            1       3   4.0   16.7000
12            1       1  58.0   26.5500
13            0       3  20.0    8.0500
14            0       3  39.0   31.2750
15            1       3  14.0    7.8542
16            1       2  55.0   16.0000
17            0       3   2.0   29.1250
19            1       3  31.0   18.0000
21            0       2  35.0   26.0000
22            0       2  34.0   13.0000
23            1       3  15.0    8.0292
24            0       1  28.0   35.5000
25            1       3   8.0   21.0750
26            1       3  38.0   31.3875
28            0       1  19.0  263.0000
31            0       1  40.0   27.7208
34            0       2  66.0   10.5000
35            0       1  28.0   82.1708
36            0       1  42.0   52.0000
38            0       3  21.0    8.0500
39            1       3  18.0   18.0000
...          ..     ...   ...       ...
857           1       1  45.0  164.8667
858           0       1  51.0   26.5500
859           1       3  24.0   19.2583
861           0       3  41.0   14.1083
862           0       2  21.0   11.5000
863           1       1  48.0   25.9292
865           0       2  24.0   13.0000
866           1       2  42.0   13.0000
867           1       2  27.0   13.8583
868           0       1  31.0   50.4958
870           0       3   4.0   11.1333
871           0       3  26.0    7.8958
872           1       1  47.0   52.5542
873           0       1  33.0    5.0000
874           0       3  47.0    9.0000
875           1       2  28.0   24.0000
876           1       3  15.0    7.2250
877           0       3  20.0    9.8458
878           0       3  19.0    7.8958
880           1       1  56.0   83.1583
881           1       2  25.0   26.0000
882           0       3  33.0    7.8958
883           1       3  22.0   10.5167
884           0       2  28.0   10.5000
885           0       3  25.0    7.0500
886           1       3  39.0   29.1250
887           0       2  27.0   13.0000
888           1       1  19.0   30.0000
890           0       1  26.0   30.0000
891           0       3  32.0    7.7500

[714 rows x 4 columns]